server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  mail:
    host: smtp.mail.ru
    port: 587
    username: c32068@mail.ru
    password: Inozemtsev1984
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://Izum4ik:Izum170809@cluster0-r3vd9.mongodb.net/IL-notifications?retryWrites=true&w=majority
